language: node_js

node_js:
  - 15
  - 14
  - 13
  - 12
  - 11
  - 10
  - 9
  - 8

before_install:
  - apt-get install libavahi-compat-libdnssd-dev

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
